version: '3.8'

services:
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    ports:
      - "${RAVENDB_PORT}:8080"   # RavenDB Studio (UI)
    environment:
      - RAVEN_Setup_Mode=None
    volumes:
      - ./ravendb_data:/var/lib/ravendb/data

  frontend:
    build:
      context: ./Web
      dockerfile: Dockerfile
    container_name: snipets-frontend
    working_dir: /app
    ports:
      - "${WEB_PORT}:3000"
    environment:
      - VITE_API_URL=http://localhost
      - VITE_API_PORT=${API_PORT}
    volumes:
      - ./Web:/app
      - /app/node_modules

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: snipets-api
    working_dir: /app
    ports:
      - "${API_PORT}:8000"
    environment:
      - RAVENDB_HOST=ravendb
      - RAVENDB_PORT=8080
      - FRONTEND_URL=http://localhost:${WEB_PORT}
    volumes:
      - ./api:/app