version: '3.8'

services:
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    ports:
      - "8082:8080"   # RavenDB Studio (UI)

  frontend:
    build:
      context: ./Web
      dockerfile: Dockerfile
    container_name: snipets-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost
      - VITE_API_PORT=8000
    volumes:
      - ./Web:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: snipets-api
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - RAVENDB_HOST=ravendb
      - RAVENDB_PORT=8080
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./api:/app